### ISSUE TITLE
Add formatter command

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#122]
I've been using a small compose to run a `black` formatter recently.

I'll try to add it to the framework, should be a no brainer.

**Comment by pdonorio** [comment]
Hey this was fun!

Implemented `black` formatter. You can just use it with:
```bash
rapydo formatter
# runs on backend 'apis' and 'tests' folders
```

You can add more folders like this:
```yaml
# create a projects/YOUR_PROJECT/confs/formatter.yml
version: '3'
services:
  formatter:
    volumes:
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/backend/WHATEVER_DIR:/workdir/WHATEVER_NAME
```
