### ISSUE TITLE
Mail sending

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#36]
We done some experiments on mail sending and we reached a working configuration:

I added on backend compose (pull or copy from upstream to update it)

```
  smtp:
    image: namshi/smtp
    networks:
      smtp_net:
        aliases:
          - ${SMTP_HOST}
```

I added to utils/project_defaults.yaml

`SMTP_HOST: smtp.dockerized.io`

Note: new release is required if utils is used as package

In my production enviroment i added:

```
services:
  backend:
    [...]
    networks:
      smtp_net:

    depends_on:
      [...]
      - smtp

  smtp:
    environment:
      ACTIVATE: 1

      SMARTHOST_ADDRESS: mail.OURHOST.it
      SMARTHOST_PORT: 587
      SMARTHOST_USER: n.surname@OURHOST.it
      SMARTHOST_PASSWORD: yourpass
      SMARTHOST_ALIASES: "*.OURHOST.it"
```

OURHOST= we know who we are
