### ISSUE TITLE
Better usage of rapydo submodules inside a fork

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#39]
The usual business for a developer that starts to write HTTP APIs with our framework is to just develop new Python classes.

The current system that uses `do` to clone submodules for rapydo packages by default at init time is wrong, just like we noticed that mounting those submodules by default is not convenient.

We should instead change this into a dedicated command like:
```bash
rapydo submodules --activate
```
This command should clone branches and change the relative configuration in `project_configuration.yaml`. 

A point to take into consideration is also that we have #33 that could also be used for this kind of operation, aiming at being the tool for rapydo developers.

**Comment by pdonorio** [comment]
By the way there is a curious bug when I use `rapydo/http-api` cloned by my self before:

```bash
[EXIT    controller.gitter:158] Unmatched local remote
Found: git@github.com:rapydo/http-api.git
Expected: https://github.com/rapydo/http-api.git
```

Probably we should split on `github.com` and remove the first char?

**Comment by pdonorio** [comment]
`frontend` at the moment is a submodule which must exists if `frontend = true`

**Comment by mdantonio** [comment]
> rapydo submodules --activate

I think that a rapydo --development flag could me more suitable

project_configuration could be changed by adding an `if: development` statement (quite similar to the `if: frontend`)

of course: `rapydo --development something => self.development = True`

Then, we just have to add the submodules mount on the backend (and celery/flower if activated):

- add options to compose via python (probably not possibile)
- add a compose file and a new -f (probably the more easy and clean solution)
- create a $mode.override.yaml (overrides are automatically read by compose) (to be created/deleted... not so clean)
- edit the $mode.yaml to add such lines (very very ugly)
- configure the $mode.yaml to use some env variable to set or not the mounts (elegant... but how to configure that?)
- other?


Then the two scenarios will be:

`rapydo start`

=> only build_base (and frontend if enabled) in submodules + no mount

`rapydo --development start`

=> backend and utilities downloaded in submodules and mounted via compose

This is an easy way to quickly switch between the two modes (for example for debugging nees in production)

**Comment by pdonorio** [comment]
> Then the two scenarios will be

approved

**Comment by pdonorio** [comment]
Related to #33

**Comment by mdantonio** [comment]
> backend and utilities downloaded in submodules and mounted via compose

The problem here is: how to mount them from controller? Are we able to pass some option to compose? Otherwise, we can create some devel.yaml containing something like:

```
backend:
    volumes:
         http-api:...
         utils:....
celery:
    .....
celeryui:
    .....
```

And by passing --development flag, we simply add this yaml to introduce mounts

`-f backend -f frontend -f devel -f vanilla`

Note: this solution is already implemented to handle collect-logs

Note2: this yaml should be moved with all other common configuration, as discussed in #79 

Note3: I add this in project 0.6.0 because if we introduce a new compose file and move it as discussed in #79, we should do that with other 0.6.0 implementation, and avoid to back here in the future

Note4: we can avoid to download submodules (httpapi and utils), if not required (i.e. without --development flag)

**Comment by pdonorio** [comment]
> add a compose file and a new -f (probably the more easy and clean solution)

> -f backend -f frontend -f devel -f vanilla

That is the way to go, yep

**Comment by mdantonio** [comment]
Added a devel.yml in confs, included when rapydo --development switch in on

This new compose add the mount of restapi and utils on both backend and celery containrs

```
version: '3'

services:
  backend:
    volumes:
      - ../submodules/http-api/restapi:/usr/local/lib/python3.6/dist-packages/restapi
      - ../submodules/utils/utilities:/usr/local/lib/python3.6/dist-packages/utilities

  celery:
    volumes:
      - ../submodules/http-api/restapi:/usr/local/lib/python3.6/dist-packages/restapi
      - ../submodules/utils/utilities:/usr/local/lib/python3.6/dist-packages/utilities


```
=> removed this mount from debug.yml

I also added in my .projectrc the following configuration, since i always want this mount active on my pc
`development: true`

**Comment by mdantonio** [comment]
Added in project_defaults:

```
  env:
    [...]
    # Path to dist-packages in backend/celery containers
    PYTHON_PATH: /usr/local/lib/python3.6/dist-packages 
```

=>

Modified devel.yml:


```
version: '3'

services:
  backend:
    volumes:
      - ../submodules/http-api/restapi:${PYTHON_PATH}/restapi
      - ../submodules/utils/utilities:${PYTHON_PATH}/utilities

  celery:
    volumes:
      - ../submodules/http-api/restapi:${PYTHON_PATH}/restapi
      - ../submodules/utils/utilities:${PYTHON_PATH}/utilities

```
