### ISSUE TITLE
Test multiple projects on restapi

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#53]
Backend unittests should be based on multiple projects to test different configurations

Coverage output from every test must be merged via coverage combine

**Comment by mdantonio** [comment]
Changed .travis to be able to execute more configuration

Moved the docker cp of .coverage from the after_success block to the script block

Modified the docker cp of .coverage to save that raw coverage file with a suffix (.coverage.$PROJECT)

By replying these commands on several project we are able to collect more .coverage files

```
for PROJECT IN a b c
    rapydo --project $PROJECT init && start
    rapydo --project $PROJECT shell tests...
    docker cp $PROJECT.......:/code.coverage .coverage.$PROJECT 
```



Added the coverage combine command. This command take all .coverage.anysuffix files and create a single .coverage file


This is the result obtained by executing a single configuration, collecting a single .coverage.template file  combined in a .coverage file sent to coveralls:

https://coveralls.io/jobs/28099856

Next: run at least two configurations and verify the merge

**Comment by mdantonio** [comment]
Now the multiple configuration work and is configured to run neo4j, sql and mongo 

for a strange bug neo4j project does not work, i'm still running template... to be fixed soon

This issue can be closed

**Comment by mdantonio** [comment]
Reopen to add parallelization of multiple runs

The current implementation is serialize. It works well but it is very slow (and will be even more slow, by adding more and more projects to test more functionalities [e.g. i'm adding celery and irods projects])

We need a parallel implementation

I implemented a parallel version by adopting a [travis build matrix ](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix) based on env variable.

It works, the all jobs are executed for every PROJECT (coverage combine, send to coveralls and, if tagged, the package deploy)

Now i'm testing the use of [build stages](https://blog.travis-ci.com/2017-05-11-introducing-build-stages)

To understand if output produced by every parallel job (.coverage.$PROJECT file) will be available at the end of the running stage

**Comment by mdantonio** [comment]
The stage mechanims work very well... the very huge problem is [data persistence](https://docs.travis-ci.com/user/build-stages/#Data-persistence-between-stages-and-jobs):

> It is important to note that jobs do not share storage, as each job runs in a fresh VM or container. If your jobs need to share files (e.g., using build artifacts from the “Test” stage for deployment in the subsequent “Deploy” stage), you need to use an external storage mechanism such as S3 and a remote scp server.

So we are able to test several projects in parallel and only if all of them pass the tests execute once the coverage and deploy steps. BUT we are unable to collect .coverage files produced by every project to combine them...

**Comment by pdonorio** [comment]
Time to look for an S3 storage? :-)

**Comment by mdantonio** [comment]
> Time to look for an S3 storage? :-)

OMG, even more complicated!

However, here a travis build with s3 to share files between stages

https://docs.travis-ci.com/user/build-stages/share-files-s3/

**Comment by mdantonio** [comment]
> Time to look for an S3 storage? :-)

I just done some tests... to be decided if such tests should be integrated into travis:

**Create a S3 storage server with docker**

https://hub.docker.com/r/scality/s3server/

`docker run -d --name s3server -p 8000:8000 scality/s3server:mem-latest`

Note: it is a in-memory server (good for our purpose)... all files are lost after stopping. remove mem-latest for persistent storage

**Access to S3 storage**

`sudo pip3 install awscli`

```
aws --endpoint-url http://localhost:8000 configure

>>> AWS Access Key ID: accessKey1
>>> AWS Secret Access Key: verySecretKey1
>>> Default region name: None
>>> Default output format: None
```

This command creates the following file: ~/.aws/credentials
```
cat ~/.aws/credentials
[default]
aws_access_key_id = accessKey1
aws_secret_access_key = verySecretKey1
```

`aws --endpoint-url http://localhost:8000 s3api create-bucket --bucket http-api`

`aws --endpoint-url http://localhost:8000 s3 ls`

```
aws --endpoint-url http://localhost:8000 s3 sync test s3://http-api
>>> upload: test/log.txt to s3://http-api/log.txt
```

```
aws --endpoint-url http://localhost:8000 s3 sync s3://http-api test2
>>> download: s3://http-api/log.txt to test2/log.txt
```

`aws --endpoint-url http://localhost:8000 s3api delete-bucket --bucket http-api`


**Use S3 from Travis**
FROM: https://docs.travis-ci.com/user/build-stages/share-files-s3/
Not tested (fix paths)

```
env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/shared
  - aws s3 sync s3://travis-build-stages-shared-storage-test/shared ~/shared

jobs:
  include:
    - stage: setup files
      script: echo one | tee > ~/shared/one
    - stage: setup files
      script: echo two | tee > ~/shared/two
    - stage: use shared files
      script:
        - cat ~/shared/*

after_success:
  - aws s3 sync ~/shared s3://travis-build-stages-shared-storage-test/shared
```

This example is missing the configuration phase...  could we use encryption to securely save s3 key/secret in the travis.yaml?

https://docs.travis-ci.com/user/encryption-keys/

**Comment by pdonorio** [comment]
`travis encrypt --add deploy.password` should be used but we didn't understand how to decrypt so far (dig more into [this](https://stackoverflow.com/questions/31519546/how-i-can-decrypt-secure-env-variables#comment78984806_44059814) if you have time)

So the best option is to add an hidden variable into repo settings:
https://stackoverflow.com/a/43263830

**Comment by mdantonio** [comment]
Added env variables to travis (Settings -> Environment Variables)

```
S3_HOST = http://130.186.13.129:4321
S3_USER = *********************
S3_PWD = *********************
```

Added after project test:

```
aws configure set aws_access_key_id $S3_USER 
aws configure set aws_secret_access_key $S3_PWD
aws --endpoint-url $S3_HOST s3api create-bucket --bucket http-api-${TRAVIS_BUILD_ID}
aws --endpoint-url $S3_HOST s3 sync ../covs s3://http-api-${TRAVIS_BUILD_ID}
```

Added before coverage combine:


```
aws configure set aws_access_key_id $S3_USER 
aws configure set aws_secret_access_key $S3_PWD

aws --endpoint-url $S3_HOST s3 sync s3://http-api-${TRAVIS_BUILD_ID} covs
```

**Comment by mdantonio** [comment]
S3 works fine

Please note that uploaded files are not deleted (but they are very small) after the use

However the S3 server is `s3server:mem-latest` and `mem` means that file are stored in memory and are not persistent on disk.... so a restart of the container should flush every previous upload

**Comment by mdantonio** [comment]
Multiple tests worked !

https://travis-ci.org/rapydo/http-api/builds/277716039

**Comment by mdantonio** [comment]
Simple docker-compose for s3:

```
version: '3'
services:
  s3server:
    image: scality/s3server:mem-latest
    ports:
      - 4321:8000
    environment:
      SCALITY_ACCESS_KEY_ID: mykey1 
      SCALITY_SECRET_ACCESS_KEY: mysecret1 

```
