### ISSUE TITLE
How to reference developing branches

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#55]
We depend too much on informations that `git` can provide to decide which version of `rapydo` is currently developed.

This is the reason why we decided to have the same branch name for all tools while developing. This has the main drawback of avoiding the possibility to develop different features inside a new release.

Looking for a solution I may propose something:

Let's have a centralized reference (an online file) to access informations about which branch is used in which release and by whom. E.g.

```bash
cat rapydo/issues/.development.yaml
```

```yaml
releases:
[...]
  "0.6.0":
    mattia:
      branch: 0.6.0-users
      description: better user management
    paolo:
      branch: 0.6.0-irods
      description: irods enhancement for eudat
  "0.6.1":
    paolo:
[...]

```

**Comment by mdantonio** [comment]
> This is the reason why we decided to have the same branch name for all tools while developing. This has the main drawback of avoiding the possibility to develop different features inside a new release.

I think that use the same branch on every repo is an acceptable assumption (without the develop tool can be cumbersome... but we can base our consideration on the use of the develop tool)

The only problem, for me, is the direct branch-to-release link (i.e. i want to implement a new feature => i open a branch named as current_release+1)

With free naming for developing branches, we have 3 scenarios:

- we can still implement minor fixes on releaes-based branches (this is optional)

When we want to release a new version we collect all branches ready to be merged: we have different scenarios:

1) we only have a single development branch X => merge X in master
2) we have more development branches (X and Y) AND a version-based branch [a.b.c.] (typically with minor fixes to be included in the _next release_) => merge X in a.b.c + merge Y in a.b.c => merge a.b.c in master.
3) we have more development branches (X and Y) BUT we don't still have a version-based branch => create a version based branch based on a development branch [X -> a.b.c], merge Y in a.b.c, merge a.b.c in master

cases 2 and 3 can be simplified by splitting different development branches in different releases

Based in these considerations, there is not big differences compared to now, just more freedom in creating branches (i.e. a more agile development) and a bit more complicated releases (that can be simplified by avoid multi-branch releases)

Just a final consideration about branches retention:

- development branches can be delete once merge in the release branch

- release branches are always associated with a tag, so could be deleted. The only motivation that i see for the retention of such branches is the detached checkout

if you checkout a tag we are detached, so you are unable to push modifications. But we really want to push modifications on an already released version?

Unitest fails on tags due to detached that do not allow some operations (e.g. rapydo update) but we do not expect to perform unitests after the release. So i image the following workflow:

- i create a development branch X (named whatever i want). I keep this branch for a number of days/weeks/months
- at the end of the development phase i merge my branch in the "next release branch" (calculated as minor/major update of the current release, based on the size of such implementations)
- after the merge i destroy the branch X and i put my modification in the release-branch a.b.c (this is a pre-release)
- after the merge of a.b.c in master i can destroy the a.b.c branch and create the a.b.c tag

**Comment by mdantonio** [comment]
Now we have a version in the project block of project_configuration

The version is reported in the releases block of project_configuration and associated to a rapydo version

Example:

```
project:
  title: My project
  description: my description
  version: "1.0.2"

releases:
  '0.9':
    type: beta
    rapydo: 0.5.5
    status: discontinued
  '1.0.0':
    type: beta
    rapydo: 0.5.6
    status: released
  '1.0.1':
    type: beta
    rapydo: 0.5.7
    status: released
  '1.0.2':
    type: beta
    rapydo: 0.6.0
    status: developing
```

This solution may not be the optimal one, but for now it works

Further improvements will be discussed and implemented in #71
