### ISSUE TITLE
Rapydo upgrade

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#71]
There's already an `upgrade` command in the controller implemented for Eudat.
Now this should work also for other project.

- How to check if I can upgrade my current project?

Git fetch and check existing remote branches. If the version exists you can switch.
There you will find in `project_configuration` which version of rapydo is associated. To check if that version exists we can [have some workaround](https://gilang.chandrasa.com/blog/how-to-get-list-of-available-versions-for-a-package-on-pypi/). If the package does not exists on `rapydo-http` then we should git fetch branches on `submodules/backend`.

- How to upgrade only rapydo components?

`rapydo upgrade --current` should upgrade components as indicated in project_configuration, if any

**Comment by mdantonio** [comment]
Vanilla projects require to specify rapydo version. This can be done in two ways:

1. projects not supporting releases: rapydo version can be specified in project block

```
project:
  title: My project
  description: Title of my project
  version: "1.0"
  rapydo: "0.5.7"
```

2. projects supporting releases: rapydo version must be specified in release block

```
releases:
  '1.0':
    type: beta
    rapydo: 0.5.7
    status: developing
```

I implemented a number of checks:

1. if you specified a rapydo version, you have to use a rapydo-controller with the same version (else: exit)
2. if you support releases your version (project.version) must be listed in releases (else: exit)
3. if you support releases your have to specify rapydo version in release block (else: exit)
4. if you specify rapydo version in both project and release and such versions are the same => warning 
4. if you specify rapydo version in both project and release and such versions are different => exit
